// <auto-generated />
using System;
using GetDataFromDBAppDbContext.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetDataWeb.Migrations
{
    [DbContext(typeof(DestinationDbContext))]
    [Migration("20230409143355_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GetDataWeb.Models.SPDest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("sDP1")
                        .HasColumnType("float");

                    b.Property<double?>("sDP10")
                        .HasColumnType("float");

                    b.Property<double?>("sDP2")
                        .HasColumnType("float");

                    b.Property<double?>("sDP255")
                        .HasColumnType("float");

                    b.Property<double?>("sDP4")
                        .HasColumnType("float");

                    b.Property<double?>("sDP6")
                        .HasColumnType("float");

                    b.Property<double?>("sDP7")
                        .HasColumnType("float");

                    b.Property<double?>("sDP8")
                        .HasColumnType("float");

                    b.Property<double?>("sDP9")
                        .HasColumnType("float");

                    b.Property<double?>("sDPBegYear")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SPDests");
                });
#pragma warning restore 612, 618
        }
    }
}
