// <auto-generated />
using System;
using GetDataFromDBAppDbContext.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetDataWeb.Migrations
{
    [DbContext(typeof(DestinationDbContext))]
    [Migration("20230505055731_ParameterValueKey")]
    partial class ParameterValueKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GetDataFromDBApp.Models.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParameterId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("GetDataFromDBApp.Models.ParameterValue", b =>
                {
                    b.Property<int>("PechId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtFirstDay")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("PechId", "ParameterId", "DtFirstDay");

                    b.HasIndex("ParameterId");

                    b.ToTable("ParameterValues");
                });

            modelBuilder.Entity("GetDataFromDBApp.Models.Pech", b =>
                {
                    b.Property<int>("PechId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PechId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PechId");

                    b.ToTable("Pechi");

                    b.HasData(
                        new
                        {
                            PechId = 1,
                            Name = "ДП-1"
                        },
                        new
                        {
                            PechId = 2,
                            Name = "ДП-2"
                        },
                        new
                        {
                            PechId = 4,
                            Name = "ДП-4"
                        },
                        new
                        {
                            PechId = 6,
                            Name = "ДП-6"
                        },
                        new
                        {
                            PechId = 7,
                            Name = "ДП-7"
                        },
                        new
                        {
                            PechId = 8,
                            Name = "ДП-8"
                        },
                        new
                        {
                            PechId = 9,
                            Name = "ДП-9"
                        },
                        new
                        {
                            PechId = 10,
                            Name = "ДП-10"
                        },
                        new
                        {
                            PechId = 255,
                            Name = "Цех"
                        });
                });

            modelBuilder.Entity("GetDataFromDBApp.Models.ParameterValue", b =>
                {
                    b.HasOne("GetDataFromDBApp.Models.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });
#pragma warning restore 612, 618
        }
    }
}
