// <auto-generated />
using System;
using GetDataFromDBAppDbContext.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetDataWeb.Migrations
{
    [DbContext(typeof(GetDataFromDBAppContext))]
    [Migration("20230329134239_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GetDataFromDBApp.Models.Parameter", b =>
                {
                    b.Property<int>("ID_Parameter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Parameter"));

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Parameter");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("GetDataFromDBApp.Models.ParameterValue", b =>
                {
                    b.Property<DateTime>("dtFistDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Parameter")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pech")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("dtFistDay");

                    b.HasIndex("ID_Parameter");

                    b.ToTable("ParameterValues");
                });

            modelBuilder.Entity("GetDataFromDBApp.Models.ParameterValue", b =>
                {
                    b.HasOne("GetDataFromDBApp.Models.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ID_Parameter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });
#pragma warning restore 612, 618
        }
    }
}
